name: mosaic components node packing build
on: 
  push:
    branches:
      - devops
jobs:        
  job1:
    node-package:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: npm build
        run: |
          cd /home/runner/work/mosaic/mosaic/packages/mosaic-components
          jq 'del(.devDependencies.cypress)' package.json > _.json && mv _.json package.json 
          npm install
          npm run build
          npm run storybook:build
		
  job2:
    node-package:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: npm build
        run: |
          cd /home/runner/work/mosaic/mosaic/packages/mosaic-esm-components
          jq 'del(.devDependencies.cypress)' package.json > _.json && mv _.json package.json 
          npm install
          npm run build
          npm run storybook:build		         
