on: 
  push:
    branches:
      - devops
jobs:
  node-package:
    runs-on: ubuntu-16.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: cypress exe  
        run: |
          pwd
          cd /home/runner/work/mosaic/mosaic/packages/mosaic-components
          npm install
          npx cypress run --parallel --record --key h5ysqc
          echo 'job completed'
		  
           
          
