
on:
  push:
    branches:
      - dev   

jobs:
  node-package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: npm build
      working-directory: ./src
      run: |
       # sh '''jq \'del(.devDependencies.cypress)\' package.json > _.json && mv _.json package.json 
        npm inatall
        npm run build
        npm run storybook:build'''          
